#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# EXAMPLE OBJECTIVE: to demonstrate omp_hello.c example 
# on Zythos with GNU compiler.
# omp_hello.c code is taken from
# https://computing.llnl.gov/tutorials/openMP/exercise.html
# This code is an OpenMP example that runs on 2 nodes with
# 6 cores and 6 OpenMP threads for each node.

# To run this code load the necessary modules.
# and specify the total number of OpenMP threads.
# This information is located under hello_ompc_gnu.slurm
# You can edit the SLURM as: emacs hello_ompc_gnu.slurm

# SLURM directives
# 
# We modify the partition to Zythos (--partition=zythos)
# Here we specify to SLURM that we want 2 nodes (--ntasks=2)
# and 6 cores (--cpus-per-task=6)
# We also replace the account name with 
# our own account name (--account=pawsey0001)
# If the account name is missing or not entered correctly,
# the SLURM does not run.
# To run this code correctly on Zythos, we comment out: --export=NONE
# If this is not commented out, the code does not run.
# To compile the code with GNU, 
# we need to load the gcc module as shown below: 
module load gcc
# We also need to load the necessary modules before module listing.
module load mpt
# Then, we set the number of threads to 12 as shown below: 
# export OMP_NUM_THREADS=12
# Therefore, the srun looks like:
# omplace -nt $OMP_NUM_THREADS ./$EXECUTABLE >> ${OUTPUT}
 
# To compile the omp_hello.c code with GNU
gcc -fopenmp omp_hello.c -o hello_omp_gnu

# To submit the job to Zythos
sbatch hello_ompc_gnu.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_helloOmpC_gnu_zythos/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/helloOmpC_gnu_zythos_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/helloOmpC_gnu_zythos_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat helloOmpC_gnu_zythos.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "
echo " "  
echo "more information about Zythos can be found at:"
echo " https://support.pawsey.org.au/documentation/pages/viewpage.action?pageId=2162999"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
