#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate lamps example on Magnus
# with GNU Environment.
# 
# lammps is an MPI code that runs on 2 nodes or more
# with 24 MPI tasks on each node.
# To run this code, we need to specify the total number of MPI tasks
# and the number of MPI tasks per node.
# We also need to change the compiler from Cray to GNU
# to be able to run this code with GNU Environment.
# We need to load the module lammps
# This information is located under lammps_mpi_gnu.slurm
# You can edit the SLURM as: emacs lammps_mpi_gnu.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 2 nodes (--nodes=2)
# To compile hello_mpi.c with GNU, we change the compiler
# from Cray to GNU as shown below:
module swap PrgEnv-cray PrgEnv-gnu
# We then load the lammps module as shown
module load lammps 
# To launch a job, we specify to aprun 48 MPI tasks (-n 48)
# with 24 tasks per node (-N 24)
# If the number of nodes changes, the N is 24 
# multiplied by number of nodes given
# Therefore, the aprun command looks like:
# aprun -n 48 -N 24 $EXECUTABLE < epm2.lmp >> ${OUTPUT}


# To submit the job to Magnus
sbatch lammps_mpi_gnu.slurm

echo "The sbatch command returns what jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo "Your job is deleted from the scratch."
echo "It is now moved to your group."
echo "Your results are now located in ${MYGROUP}/lmp_mpi_results/"
echo "To change to your jobID directory, type:"
echo "cd ${MYGROUP}/lmp_mpi_results/jobID/"
echo "To view the results, use the cat command and type:"
echo "cat lammps_mpi.log"

# To swap from GNU environment back to the default program environment:
module swap PrgEnv-gnu PrgEnv-cray
