#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate lamps example on Magnus
# with GNU Environment.
# 
# lammps is an MPI code that runs on 2 nodes or more
# with 24 MPI tasks on each node.
# To run this code, we need to specify the total number of MPI tasks
# and the number of MPI tasks per node.
# We also need to change the compiler from Cray to GNU
# to be able to run this code with GNU Environment.
# We need to load the module lammps
# This information is located under lammps_mpi_gnu.slurm
# You can edit the SLURM as: emacs lammps_mpi_gnu.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 2 nodes (--nodes=2)
# To compile hello_mpi.c with GNU, we change the compiler
# from Cray to GNU as shown below:
module swap PrgEnv-cray PrgEnv-gnu
# We then load the lammps module as shown
module load lammps 
# To launch a job, we specify to aprun 48 MPI tasks (-n 48)
# with 24 tasks per node (-N 24)
# If the number of nodes changes, the N is 24 
# multiplied by number of nodes given
# Therefore, the aprun command looks like:
# aprun -n 48 -N 24 $EXECUTABLE < epm2.lmp >> ${OUTPUT}


# To submit the job to Magnus
sbatch lammps_mpi_gnu.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_lammps_mpi/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/lammps_mpi_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/lammps_mpi_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat lammps_mpi.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "

echo " "  
echo "more information about Magnus can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Magnus+User+Guide"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
