#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate swan openmp example 
# on kaya with the Intel compiler toolchain Environment.

# SWAN is a third-generation wave model, developed at 
# Delft University of Technology, that computes random, 
# short-crested wind-generated waves in coastal regions 
# and inland waters.
 
# with 20 OpenMP threads on a node.
# To run this code, we need to specify the total 
# number of threads per node.
# This information is located under swan.slurm
# You can edit the SLURM as: nano swan.slurm 

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1 or -N 1)
# grasp is compiled with GNU, we change the compiler
# from GNU as shown below:
module load intel/2020.4 metis/5.1.0 swan/41.41

# To launch a job, we specify the input file f32har01.swn number of threads 20 (-n 20)

# Therefore, the run command looks like:
# swanrun -input f32har01.swn -omp 20 >> ${OUTPUT}


# To submit the job to Kaya
jobid=$(sbatch --parsable swan.slurm)

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_swan/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/swan_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/swan_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat f32har01.prt"
echo " "
echo " kaya user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "
echo " "  
#echo "more information about Kaya can be found at:"
#echo " https://docs.hpc.uwa.edu.au/docs/"
#echo " "
#echo "more information about SLURM and srun can be found at:"
#echo " https://docs.hpc.uwa.edu.au/docs/slurm/"
#echo " "
echo " "
