#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBjECTIVE: to demostrate hybrid_hello.f90 example
# on Zeus with Intel Compiler. This is a mixed-mode job
# which includes both MPI and OpenMP jobs.
# cp the hybrid_hello.f90 source code
cp $GE_DIR/src/hybrid_hello.f90 .


 
# To run this code load the necessary modules.,
# specify the total number of MPI tasks and
# the number of OpenMP threads.
# This information is located under hello_hybrid_intel.slurm
# You can edit the SLURM as: emacs hello_hybrid_intel.slurm 

# SLURM directives
# 
# Here specify to SLURM that we want 2 nodes (--node=2)

# To run this code correctly on Zeus, 
# we need to remove --export=NONE
# If it is still included in the SLURM, 
# the code does not compile.
# To compile with Intel compiler, we need to unload gcc module
# and load the intel module as shown below:
module unload gcc
module load intel
# Then, we load the other necessary modules before listing.
module load mpt
# This script requires 2 nodes and runs 1 MPI process with
# 16 OpenMP threads on each intel compiled executable.
# Hence, we set the number of threads to 16 as shown below: 
# export OMP_NUM_THREADS=16
# Therefore, the srun command looks like:
# srun --mpi=pmi2 -n 2 -N 2 ./$EXECUTABLE >> ${OUTPUT}

# To compile the hybrid_hello.f90 code with Intel compiler
mpif90 -O2 -qopenmp hybrid_hello.f90 -o hello_hybrid_intel

# To submit the job to Zeus
sbatch hello_hybrid_intel.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_fortranHybrid_intel/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/fortranHybrid_intel_results_zeus/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/fortranHybrid_intel_results_zeus/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat fortranHybrid_intel.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "
echo " "  
echo "more information about Zeus/Zython can be found at:"
echo " https://support.pawsey.org.au/documentation/pages/viewpage.action?pageId=2162999"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "

