#!/bin/bash --login
#BSUB -J GE-gcc-MPI_gnu
#BSUB -q pge410
#BSUB -n 32 
#BSUB -W 00:10
#BSUB -x
#BSUB -R "span[ptile=32]"
#BSUB -a "p8aff(1,1,1,balance)"
#BSUB -e gnu_MPIHello-%J.e
#BSUB -o gnu_MPIHello-%J.o

# To compile with GNU compiler, load the gcc module
module load use.paragon 
module load gcc6/6.4.0 openmpi/3.0.1

# leave in, it lists the environment loaded by the modules
module list
rpm -qa | grep ibm_smpi

#  Note:  is a unique number for every job.
#  These are generic variables
EXECUTABLE=hello_mpi_gnu
SCRATCH=$PG/run_ccMPI_gnu/$LSB_REMOTEJID
###############################################
# Creates a unique directory in the SCRATCH directory for this job to run in.
if [ ! -d $SCRATCH ]; then 
    mkdir -p $SCRATCH 
fi 
echo SCRATCH is $SCRATCH

###############################################
# declare the name of the output file or log file
OUTPUT=410-MPI_gnu.log

#############################################
#   Copy input files to $SCRATCH
#   then change directory to $SCRATCH

mv $PG/data_exe/$EXECUTABLE $SCRATCH

cd $SCRATCH

ulimit -s 10240
ppc64_cpu --info

mpirun -report-bindings ./$EXECUTABLE >> ${OUTPUT}

##############################################
# create a unique test file in the PG directory
# this will signal the laucher script that the job as finished
# so it it can copy the results back to CDS

touch ${PG}/cpt$LSB_REMOTEJID

echo cc MPI_gnu job finished at  `date`
