#!/bin/bash --login

# SLURM directives
#
# Here we specify to SLURM we want one node (--nodes=1) with
# a wall-clock time limit of one minute (--time=00:01:00).
#
# Replace hello_numa_ranga with appropriate project name
# following --account (e.g., --account=project123)

#SBATCH --nodes=1
#SBATCH --time=00:01:00
#SBATCH --account =hello_numa_ranga
#SBATCH --export=NONE

# We specify to aprun that there is one task (-n 1) and we have
# 12 threads (-d 12) placed explicitly on cores 0-11 (-cc 0-11).
#
# We must also set OMP_NUM_THREADS=12

export OMP_NUM_THREADS=12
aprun -n 1-d 12 -cc 0-11 ./hello_numa_ranga
