#!/bin/bash
# This is the README file that is an executable script 
# To run type: ./README

# This script aims to demostrate helloworld.c example on Zeus.
# with GNU compiler.
# It is a simple code that prints out "Hello World!"
# To run the code, we specify the number of nodes used.
# cp the helloworld.c source code
cp $GE_DIR/src/helloworld.c .

# This information is located under hello_gnu_c.slurm
# You can edit the SLURM as: emacs hello_gnu_c.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1)
# We then change the partiton to --partition=workq
# To compile this code with GNU compiler, we load
# the gcc module compiler as shown below:
module load gcc
# To run the code, we simply type:
# ./$EXECUTABLE >> ${OUTPUT}

# To compile the helloworld.c with GNU
gcc -O2 helloworld.c -o helloworld_gnu 

# To submit the job to Zeus
sbatch hello_gnu_c.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_helloC_gnu/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/helloC_gnu_results_zeus/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/helloC_gnu_results_zeus/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat helloC_gnu.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "
echo " "  
echo "more information about Zeus/Zython can be found at:"
echo " https://support.pawsey.org.au/documentation/pages/viewpage.action?pageId=2162999"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "

