#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate running lsdyna example 
# on kaya.
# 

cp $GE_DIR/src/lsdyna/foam.k .


# To run this code, we need to specify the number of nodes used.
# This information is located under helloworld_gnu.slurm
# You can edit the SLURM as: emacs helloworld_gnu.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1)
# To compile the code with the GNU environment, we change
# the environment from Cray to GNU as shown below:
module load ansys/v231
# To run the code, we simply type:
# lsdyna i=$INPUT ncpu=36 memory=1000000000

# To submit the job to kaya
jobid=`sbatch --parsable lsdyna-foam.slurm`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_lsdyna_ystatic/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/lsdyna_ystatic_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/lsdyan_ystatic_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat "
echo " "
echo " kaya user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "

echo " "  
echo " "
