#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBjECTIVE: to demostrate hello_mpi.f90 example
# on Zeus with PGI compiler.
# This code is an MPI example that requests 2 nodes with 16
# MPI tasks running on each node.
# This example is taken from:
# https://people.sc.fsu.edu/~jburkardt/f_src/hello_mpi/hello_mpi.html
# cp the hello_mpi.f90 source code
cp $GE_DIR/src/hello_mpi.f90 .
# patch hello_mpi.f90
sed -i "s/use mpi/include \"mpif.h\"/g" hello_mpi.f90

 
# To run this code load the necessary modules.
# and specify the total number of MPI tasks.
# This information is located under hello_mpi_pgi.slurm
# You can edit the SLURM as: emacs hello_mpi_pgi.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 2 nodes (--nodes=2)
# Then, we modify the partition to --partition==workq
# To run this code correctly on Zeus, we need to remove --export=NONE
# If it is still included in the SLURM, the code does not compile.
# To compile the code with PGI compiler, we need to unload the
# gcc module and then load the pgi module as shown below:
module unload gcc
module load pgi
# We then load the necessary modules before module listing.
module load mpt
# We also specify to srun that 32 MPI tasks are required. (-n 32)
# with 2 nodes (-N 2) given that 
# there are 16 MPI tasks per node.
# For the correct operation, MPI also needs to be specified to srun
# via the option "--mpi=pmi2"
# Therefore, the srun command looks like:
# srun --mpi=pmi2 -n 32 -N 2 ./$EXECUTABLE >> ${OUTPUT}
 
# To compile the hello_mpi.f90 code with PGI
pgf90 -Mmpi=sgimpi hello_mpi.f90 -o hello_mpi_pgi

# To submit the job to Zeus
sbatch hello_mpi_pgi.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_fortranMPI_pgi/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/fortranMPI_pgi_results_zeus/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/fortranMPI_pgi_results_zeus/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat fortranMPI_pgi.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "
echo " "  
echo "more information about Zeus/Zython can be found at:"
echo " https://support.pawsey.org.au/documentation/pages/viewpage.action?pageId=2162999"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "

