#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#  
# Example OBJECTIVE: to demonstrate hello_world.f90 example 
# with Intel compiler on Zythos.
# hello_world.f90 is a simple FORTRAN code prints "Hello World!" 
# and runs on a single node.
# cp the hello_world.f90 source code
cp $GE_DIR/src/hello_world.f90 .


# To run this code, we need to specify the number of nodes used
# and change from GNU compiler to Intel.
# This information is located under hello_fortran_intel.slurm
# You can edit the SLURM as: emacs hello_fortran_intel.slurm &

# SLURM directives
# 
# We change the partition to zythos (--partition=zythos)
# Here we specify to SLURM we want 1 node (--ntasks=1)
# We then replace the account name 
# with our own account name (--account=pawsey0001)
# If the account name is missing or not entered correctly,
# the SLURM does not run.
# To run this code correctly, we also need to remove --export=NONE
# from the SLURM. If not removed, the code does not compile.
# To compile this code with Intel, we swap
# from GNU to Intel as shown below:
module unload gcc
module load intel
# To run the code, we simply type:
# ./$EXECUTABLE >> ${OUTPUT}

# To compile the hello_world.f90 code with Intel
ifort -O2 hello_world.f90 -o hello_fortran_intel

# To submit the job to Zythos
sbatch hello_fortran_intel.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_fortran_helloworld_intel_zythos/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/fortran_helloworld_intel_zythos_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/fortran_helloworld_intel_zythos_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat fortran_helloworld_intel_zythos.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "
echo " "  
echo "more information about Zythos can be found at:"
echo " https://support.pawsey.org.au/documentation/pages/viewpage.action?pageId=2162999"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
