#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate hello_cuda.cu example
# on Zythos with GNU compiler. 
# This example is taken from:
# https://www.pdc.kth.se/resources/computers/historical-computers/zorn/how-to/how-to-compile-and-run-a-simple-cuda-hello-world
# hello_cuda.cu is a CUDA code requiring a single GPU node.
# cp the hello_cuda.cu source code
cp $GE_DIR/src/hello_cuda.cu .


# To run this code, we need to change the partition, 
# specify the number of nodes, cores and the GPU constraint.
# and load the necessary modules.
# This information is located under hello_cuda_gnu.slurm
# You can edit the SLURM as: emacs hello_cuda_gnu.slurm &

# SLURM directives
# 
# Here we change the partition to Zythos (--partition==zythos)
# Then, we specify to SLURM we want 1 node (--ntasks=1)
# with 6 cores (--cpus-per-task=6)
# We also specify to SLURM a single GPU node (--gres=gpu:1)
# We replace the account name 
# with our own account name (--account=pawsey0001)
# If the account name is missing or not entered correctly,
# the SLURM does not run.
# To run this code correctly, we need to remove --export=NONE
# If it is included in the SLURM, the code does not run properly.
# We also need to load the necessary modules 
# before module listing as shown below:
module load cuda
# To run this code, we simply type:
# ./$EXECUTABLE >> ${OUTPUT}

# To compile the hello_cuda.cu code with GNU compiler
nvcc hello_cuda.cu -o hello_cuda_gnu

# To submit the job to Zythos
sbatch hello_cuda_gnu.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_hello_CUDA_gnu_zythos/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/hello_CUDA_gnu_zythos_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/hello_CUDA_gnu_zythos_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat hello_CUDA_gnu_zythos.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "
echo " "  
echo "more information about Zythos can be found at:"
echo " https://support.pawsey.org.au/documentation/pages/viewpage.action?pageId=2162999"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
