#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBjECTIVE: to demostrate hello_mpi.c example
# on Zeus with GNU compiler. 
# This code is an MPI example that requests 2 nodes with 16
# MPI tasks running on each node.
# This example is taken from:
# https://www.dartmouth.edu/~rc/classes/intro_mpi/hello_world_ex.html
# To run this code, we need to edit the partition, 
# load the necessary modules
# and specify the total number of MPI tasks.
# This information is located under hello_mpi_gnu.slurm
# You can edit the SLURM as: emacs hello_mpi_gnu.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 2 nodes (--nodes=2)
# Then, we modify the partition to --partition==workq
# To run this code correctly on Zeus, we need to remove --export=NONE
# If it is still included in the SLURM, the code does not compile.
# We then load the necessary modules before module listing.
# module load gcc
# module load mpt
# We also specify to srun that 32 MPI tasks are required. (-n 32)
# with 2 nodes (-N 2) given that 
# there are 16 MPI tasks per node.
# For the correct operation, MPI also needs to be specified to srun
# via the option "--mpi=pmi2"
# Therefore, the srun command looks like:
# srun --mpi=pmi2 -n 32 -N 2 ./$EXECUTABLE >> ${OUTPUT}
 
# To compile the hello_mpi.c code with GNU
mpicc hello_mpi.c -o hello_mpi_gnu

# To submit the job to Zeus
sbatch hello_mpi_gnu.slurm

echo "The sbatch command returns what jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo "Your job is deleted from the scratch."
echo "It is now moved to your group."
echo "Your results are now located in ${MYGROUP}/hellompi_gnu_results_zeus/"
echo "To change to your jobID directory, type:"
echo "cd ${MYGROUP}/hellompi_gnu_results_zeus/jobID/"
echo "To view the results, use the cat command and type:"
echo "cat hello_mpi_gnu.log"

