#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate hello_mpi.f90 example 
# on KAYA on GNU Environment.
# hello_mpi.f90 code is taken from
# https://people.sc.fsu.edu/~jburkardt/f_src/hello_mpi/hello_mpi.f90
# cp the hello_mpi.f90 source code
cp $GE_DIR/src/hello_mpi.f90 .

# hello_mpi.f90 is an MPI code that runs on 2 nodes 
# with 20 MPI tasks on each node.
# To run this code, we need to specify the total number of MPI tasks
# and the number of MPI tasks per node.
# This information is located under hello_mpi_gnu.slurm
# You can edit the SLURM as: emacs hello_mpi_gnu.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 2 nodes (--nodes=2)
# To compile hello_mpi.c with GNU.  
# This will load the "default" versions
module load gcc/9.4.0 openmpi
# To launch a job, we specify to srun 20 MPI tasks (-n 20)
# with 10 tasks per node (-N 10)
# Therefore, the srun command looks like:
# srun -N 2 -n 20 ./$EXECUTABLE >> ${OUTPUT}

# To compile the hello_mpi.f90 code with GNU compiler
mpif90 -O2 hello_mpi.f90 -o hello_mpi_gnu

# To submit the job to Magnus
jobid=$(sbatch --parsable  hello_mpi_gnu.slurm)

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_fortranMPI_gnu/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/fortranMPI_gnu_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/fortranMPI_gnu_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat fortranMPI_gnu.log"
echo " "
echo " KAYA user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "

echo " "  
echo "more information about UWAHPC and Kaya can be found at:"
echo " https://uniwa.sharepoint.com/teams/EXT-UWA-HPC"
echo " "
echo "more information about SLURM and srun can be found at:"
echo " https://docs.hpc.uwa.edu.au/docs/ "
echo " "
echo " "
