#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBjECTIVE: to demostrate hello_hybrid.c example
# on Zythos with Intel Compiler. This is a mixed-mode job
# which includes both MPI and OpenMP jobs.
# hello_hybrid.c code is taken from
# http://www.slac.stanford.edu/comp/unix/farm/mpi_and_openmp.html
# To run this code, we need to edit the partition, 
# load the necessary modules,
# specify the total number of nodes, cores per node and
# the number of OpenMP threads.
# This information is located under hello_hybrid_intel.slurm
# You can edit the SLURM as: emacs hello_hybrid_intel.slurm &

# SLURM directives
# 
# We the modify the partition to --partition==zythos
# Here specify to SLURM that we want 4 nodes (--ntasks=4)
# We then specify the number of cores for the NUMA region. (--cpus-per-task=6)
# We also replace the account name 
# with our own account name (--account=pawsey0001)
# If the account name is missing or not entered correctly,
# the SLURM does not run.
# To run this code correctly on Zythos, we need to remove --export=NONE
# If it is still included in the SLURM, the code does not compile.
# To compile with Intel compiler, we need to unload 
# the gcc compiler as shown below:
# module unload gcc
# Then, we load the necessary modules before module listing.
# module load intel
# module load mpt
# We also set the number of threads to 6 as shown below: 
# export OMP_NUM_THREADS=6
# Therefore, the mpirun command looks like:
# mpirun -np 4 omplace -nt $OMP_NUM_THREADS ./$EXECUTABLE >> ${OUTPUT}
 
# To compile the hello_hybrid.c code with Intel compiler
mpicc -qopenmp hello_hybrid.c -o hello_hybrid_intel

# This code also can be compiled with -openmp wrapper as shown:
# mpicc -openmp hello_hybrid.c -o hello_hybrid_intel

# To submit the job to Zythos
sbatch hello_hybrid_intel.slurm

echo "The sbatch command returns what jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo "Your job is deleted from the scratch."
echo "It is now moved to your group."
echo "Your results are now located in ${MYGROUP}/hybrid_intel_zythos_results/"
echo "To change to your jobID directory, type:"
echo "cd ${MYGROUP}/hybrid_intel_zythos_results/jobID/"
echo "To view the results, use the cat command and type:"
echo "cat hello_hybrid_intel.log"
