#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate running a structure example 
# in GNU environment on Kaya.
# cp the helloworld.c source code
cp $GE_DIR/src/helloworld.c .


# To run this code, we need to specify the number of nodes used.
# This information is located under structure.slurm
# You can edit the SLURM as: nano structure.slurm 

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1)

# To run the code, we simply type:
# srun -n 1 ./$EXECUTABLE >> ${OUTPUT}

# To submit the job to kaya
jobid=$(sbatch --parsable structure.slurm)

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_structure/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/structure_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/structure_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat struct.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "

echo " "  
echo "more information about Magnus can be found at:"
echo " https://uniwa.sharepoint.com/teams/EXT-UWA-HPC"
echo " "
echo "more information about SLURM and srun can be found at:"
echo " https://docs.hpc.uwa.edu.au/docs/"
echo " "
echo " "
