#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBjECTIVE: to demonstrate hybrid_hello.f90 example
# on Zythos with GNU Compiler. This is a mixed-mode job
# which includes both MPI and OpenMP jobs.
# To run this code, we need to edit the partition, 
# load the necessary modules,
# specify the total number of nodes, cores per node and
# the number of OpenMP threads.
# This information is located under hello_hybrid_gnu.slurm
# You can edit the SLURM as: emacs hello_hybrid_gnu.slurm &

# SLURM directives
# 
# We modify the partition to Zythos (--partition==zythos)
# Here specify to SLURM that we want 4 nodes (--ntasks=4)
# We then specify the number of cores for the NUMA region (--cpus-per-task=6)
# We also replace the account name 
# with our own account name (--account=pawsey0001)
# If the account name is missing or not entered correctly,
# the SLURM does not run.
# To run this code correctly, we need to remove --export=NONE
# If it is still included in the SLURM, the code does not compile.
# Default loaded compiler module is gcc module.
# Therefore to compile with GNU compiler, we need to load 
# the gcc compiler and unload unnecessary modules as shown below:
module load gcc
module unload pgi
# Then, we load the necessary modules before module listing.
module load mpt
# We also set the number of threads to 6 as shown below: 
# export OMP_NUM_THREADS=6
# Therefore, the mpirun command looks like:
# mpirun -np 4 omplace -nt $OMP_NUM_THREADS ./$EXECUTABLE >> ${OUTPUT}
 
# To compile the hybrid_hello.f90 code with GNU compiler
mpif90 -O2 -fopenmp hybrid_hello.f90 -o hello_hybrid_gnu

# To submit the job to Zythos
sbatch hello_hybrid_gnu.slurm

echo "The sbatch command returns what jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo "Your job is deleted from the scratch."
echo "It is now moved to your group."
echo "Your results are now located in ${MYGROUP}/zythoshybrid_gnu_results/"
echo "To change to your jobID directory, type:"
echo "cd ${MYGROUP}/zythoshybrid_gnu_results/jobID/"
echo "To view the results, use the cat command and type:"
echo "cat hello_hybrid_gnu.log"
