#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate helloworld.c example 
# in Cray environment on Magnus.
# helloworld.c is a simple c code that prints "Hello World!" 
# and runs on a single node.
# To run this code, we need to specify the number of nodes used.
# This information is located under helloworld_cray.slurm
# You can edit the SLURM as: emacs helloworld_cray.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1)
# To compile the code on Cray, we load the Cray environment:
# module load PrgEnv-cray
# To run the code, we simply type:
# ./$EXECUTABLE >> ${OUTPUT}

# To compile the helloworld.c code on Cray
cc -O2 helloworld.c -o helloworld_cray

# To submit the job to Magnus
sbatch helloworld_cray.slurm

echo "The sbatch command returns what jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo "Your job is deleted from the scratch."
echo "It is now moved to your group."
echo "Your results are now located in ${MYGROUP}/helloc_cray_results/"
echo "To change to your jobID directory, type:"
echo "cd ${MYGROUP}/helloc_cray_results/jobID/"
echo "To view the results, use the cat command and type:"
echo "cat helloworld_cray.log"
