#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate hybrid_hello.f90 example
# on Zythos with Intel Compiler. This is a mixed-mode job
# which includes both MPI and OpenMP parallelization.
# cp the hybrid_hello.f90 source code
cp $GE_DIR/src/hybrid_hello.f90 .


 
# To run this code load the necessary modules.,
# specify the total number of nodes, cores per node and
# the number of OpenMP threads.
# This information is located under hello_hybrid_intel.slurm
# You can edit the SLURM as: emacs hello_hybrid_intel.slurm &


# SLURM directives
# 
# We modify the partition to Zythos (--partition==zythos)
# Here specify to SLURM that we want 4 nodes (--ntasks=4)
# We then specify the number of cores for the NUMA region (--cpus-per-task=6)
# We also replace the account name 
# with our own account name (--account=pawsey0001)
# If the account name is missing or not entered correctly,
# the SLURM does not run.
# To run this code correctly on Zythos, we need to remove --export=NONE
# If it is still included in the SLURM, the code does not compile.
# To compile with Intel compiler, we need to unload the gcc module
# and load the intel module as shown below:
module unload gcc
module load intel
# Then, we load the necessary modules before module listing.
module load mpt
# We also set the number of threads to 6 as shown below: 
# export OMP_NUM_THREADS=6
# Therefore, the mpirun command looks like:
# mpirun -np 4 omplace -nt $OMP_NUM_THREADS ./$EXECUTABLE >> ${OUTPUT}

# To compile the hybrid_hello.f90 code with Intel compiler
mpif90 -qopenmp hybrid_hello.f90 -o hello_hybrid_intel

# To submit the job to Zythos
sbatch hello_hybrid_intel.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_fortranHybrid_intel_zythos/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/fortranHybrid_intel_zythos_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/fortranHybrid_intel_zythos_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat fortranHybrid_intel_zythos.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "
echo " "  
echo "more information about Zythos can be found at:"
echo " https://support.pawsey.org.au/documentation/pages/viewpage.action?pageId=2162999"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
