#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate hello_world.f90 example 
# in Intel environment on Kaya.
# hello_world.f90 is a serial FORTRAN code and 
# It prints "Hello World!" and runs on a single node.
# cp the hello_world.f90 source code
cp $GE_DIR/src/hello_world.f90 .


# To run this code, we need to specify the number of nodes used
# and load the Intel OneAPI compiler environment .
# This information is located under hello_fortran_intel.slurm
# You can edit the SLURM script using: nano hello_fortran_intel.slurm 

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1 or -N 1)
# To compile this code in Intel Oneapi Environment, we load:
module use /uwahpc/centos8/modulefiles/oneapi-2023.0
module load compiler

# To run the code, we simply type:
# srun -n 1 ./$EXECUTABLE >> ${OUTPUT}

# To compile the hello_world.f90 code
ifx -O2 hello_world.f90 -o hello_fortran_intel

# To submit the job to Kaya
jobid=$(sbatch --parsable hello_fortran_intel.slurm)

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_fortran_helloworld_intel/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/fortran_helloworld_intel_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/fortran_helloworld_intel_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat fortran_helloworld_intel.log"
echo " "
echo " Kaya user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable that is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable thatis set to $MYGROUP"
echo " example:  cd \$MYGROUP "

echo " "  
echo " more information about Kaya can be found at:"
echo " https://uniwa.sharepoint.com/teams/EXT-UWA-HPC"
echo " "
echo " more information about SLURM and srun can be found at:"
echo " https://docs.hpc.uwa.edu.au/docs/slurm/"
echo " "
echo " "
