#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README 
# 
# Example OBjECTIVE: to demostrate omp_hello.c example on Magnus
# with GNU Environment where threads are restricted 
# to a single NUMA region of 12 cores. 
# omp_hello.c is taken from 
# https://computing.llnl.gov/tutorials/openMP/exercise.html
# cp the omp_hello.c source code
cp $GE_DIR/omp_hello.c .


# To run this code,we need to specify the number of tasks
# and the number of threads.
# We also need to swap from Cray Environment to GNU 
# to compile the code on GNU Environment.
# This information is located under hello_numa_gnu.slurm
# You can edit the SLURM as: emacs hello_numa_gnu.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1)
# To compile this code with GNU, we need to change
# the environment from Cray to GNU as shown below:
module swap PrgEnv-cray PrgEnv-gnu
# Then, we set the total number of threads to 12
# export OMP_NUM_THREADS=12
# To launch a job, we specify to aprun 1 task (-n 1)
# with 12 threads (-d 12)
# placed expilicitly on cores 0-11 (-cc 0-11)
# Therefore, the aprun command looks like: 
# aprun -n 1 -d 12 -cc 0-11 ./$EXECUTABLE >> ${OUTPUT}

# To compile the omp_hello.c code on GNU Environment
cc -O2 -fopenmp omp_hello.c -o hello_numa_gnu

# To submit the job to Magnus
sbatch hello_numa_gnu.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_hello_NUMA_gnu/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/hello_NUMA_gnu_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/hello_NUMA_gnu_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat hello_NUMA_gnu.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "

echo " "  
echo "more information about Magnus can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Magnus+User+Guide"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
