#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate KAT - the K-mer Analysis 
# Toolkit example in gnu environment on kaya

# cp the example data files to the getexample-dir
cp -r $GE_DIR/src/kat_data .

# To run this code, we need to specify the number of nodes used.
# This information is located under helloworld_gnu.slurm
# You can edit the SLURM as: emacs helloworld_gnu.slurm &

# SLURM directives
# Here we specify to SLURM we want 1 node (--nodes=1)
#

# To submit the job to kaya

jobid=$(sbatch --parsable kat.slurm)

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_kat/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/kat_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/kat_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat kat-run.log"
echo " "
echo " kaya user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "

echo " "  
#echo "more information about Magnus can be found at:"
#echo " https://support.pawsey.org.au/documentation/display/US/Magnus+User+Guide"
#echo " "
#echo "more information about SLURM and aprun can be found at:"
#echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
#echo " "
echo " "
