#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate hello_hybrid.c example
# on Zythos with GNU Compiler. This is a mixed-mode job
# which includes both MPI and OpenMP parallelization.
# hello_hybrid.c code is taken from
# http://www.slac.stanford.edu/comp/unix/farm/mpi_and_openmp.html
 
# To run this code load the necessary modules.,
# specify the total number of nodes, cores per node and
# the number of OpenMP threads.
# This information is located under hello_hybrid_gnu.slurm
# You can edit the SLURM as: emacs hello_hybrid_gnu.slurm &

# SLURM directives
# 
# We modify the partition to Zythos (--partition==zythos)
# Here specify to SLURM that we want 4 nodes (--ntasks=4)
# We then specify the number of cores for the NUMA region (--cpus-per-task=6)
# We also replace the account name 
# with our own account name (--account=pawsey0001)
# If the account name is missing or not entered correctly,
# the SLURM does not run.
# To run this code correctly on Zythos, we need to remove --export=NONE
# If it is still included in the SLURM, the code does not compile.
# To compile with GNU compiler, we need to load 
# the gcc compiler as shown below:
module load gcc
# Then, we load the necessary modules before module listing.
module load mpt
# We also set the number of threads to 6 as shown below: 
# export OMP_NUM_THREADS=6
# Therefore, the mpirun command looks like:
# mpirun -np 4 omplace -nt $OMP_NUM_THREADS ./$EXECUTABLE >> ${OUTPUT}
 
# To compile the hello_hybrid.c code with GNU compiler
mpicc -fopenmp hello_hybrid.c -o hello_hybrid_gnu

# To submit the job to Zythos
sbatch hello_hybrid_gnu.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_hello_hybrid_c_gnu_zythos/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/hello_hybrid_c_gnu_zythos_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/hello_hybrid_c_gnu_zythos_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat hello_hybrid_c_gnu_zythos.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "
echo " "  
echo "more information about Zythos can be found at:"
echo " https://support.pawsey.org.au/documentation/pages/viewpage.action?pageId=2162999"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
