#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate hello_world.f90 example 
# in GNU environment on Magnus.
# hello_world.f90 is a serial FORTRAN code and 
# It prints "Hello World!" and runs on a single node.
# To run this code, we need to specify the number of nodes used
# and change from Cray Environment to GNU.
# This information is located under hello_fortran_gnu.slurm
# You can edit the SLURM as: emacs hello_fortran_gnu.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1)
# To compile this code in GNU Environment, we swap
# from Cray to GNU as shown below:
module swap PrgEnv-cray PrgEnv-gnu
# To run the code, we simply type:
# aprun -n 1 ./$EXECUTABLE >> ${OUTPUT}

# To compile the hello_world.f90 code
ftn -O2 hello_world.f90 -o hello_fortran_gnu

# To submit the job to Magnus
sbatch hello_fortran_gnu.slurm

echo "The sbatch command returns what jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo "Your job is deleted from the scratch."
echo "It is now moved to your group."
echo "Your results are now located in ${MYGROUP}/hellofortran_gnu_results/"
echo "To change to your jobID directory, type:"
echo "cd ${MYGROUP}/hellofortran_gnu_results/jobID/"
echo "To view the results, use the cat command and type:"
echo "cat hello_fortran_gnu.log"

# To swap from GNU environment to the default program environment:
module swap PrgEnv-gnu PrgEnv-cray
