#!/bin/bash
# This is the README file that is an executable script to demonstrate
# omp_hello.c example on zythos
# The code is run in the intel environment
# To run this code, specify the total number of processes per node
# and the number of processes per node.
# This information is located under hello_ompc_intel.slurm
# You can edit the SLURM as: emacs hello_ompc_intel.slurm

# SLURM directives
# 
# Here we specify to SLURM we want 2 tasks (--ntasks=2)
# Replace the account name with your account name (--account=interns2016)

# To compile the omp_hello.c code

icc -O2 -qopenmp omp_hello.c -o omp_hello

# To submit the job to zythos

sbatch hello_ompc_intel.slurm

# To view when the job starts

squeue -u $USER

echo "Your jobID is returned with the sbatch command."
echo "Your job is deleted from the scratch."
echo "It is now moved to your group."
echo "Your results are now located in /${MYGROUP}/zythos_omp.intel_results/"
echo "To change to your jobID directory, type:"
echo "cd /${MYGROUP}/zythos_omp.intel_results/jobID/"
echo "To view the results, use the cat command and type:"
echo "cat omp_hello.log"
