#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBjECTIVE: to demonstrate hello_mpi.f90 example
# on Zythos with GNU compiler.
# This code is an MPI example that requests 4 nodes with 6 cores 
# each giving 24 cores in total.
# This example is taken from:
# https://people.sc.fsu.edu/~jburkardt/f_src/hello_mpi/hello_mpi.html
# To run this code, we need to edit the partition, the number of nodes
# and cores and load the necessary modules.
# This information is located under hello_mpi_gnu.slurm
# You can edit the SLURM as: emacs hello_mpi_gnu.slurm &

# SLURM directives
# 
# We modify the partition to Zythos (--partition==zythos)
# Here we specify to SLURM we want 4 nodes (--ntasks=4)
# We also specify total number of cores per node. (--cpus-per-task=6)
# We, then edit the account name. (--account=pawsey0001)
# If the account name is missing or not entered correctly, 
# the SLURM does not run.
# To run this code correctly on Zythos, we also need to remove --export=NONE
# If it is still included in the SLURM, the code does not compile.
# To compile the code with GNU compiler, we need to load gcc as shown below:
# module load gcc
# We then load the necessary modules before module listing.
# module load mpt
# We also specify to mpirun that there are 24 cores in total (-np 24)
# Therefore, the mpirun command looks like:
# mpirun -np 24 ./$EXECUTABLE >> ${OUTPUT
 
# To compile the hello_mpi.f90 code
mpif90 -O2 hello_mpi.f90 -o hello_mpi_gnu

# To submit the job to Zythos
sbatch hello_mpi_gnu.slurm

echo "The sbatch command returns what jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo "Your job is deleted from the scratch."
echo "It is now moved to your group."
echo "Your results are now located in ${MYGROUP}/zythos_hellompi_gnu_results/"
echo "To change to your jobID directory, type:"
echo "cd ${MYGROUP}/zythos_hellompi_gnu_results/jobID/"
echo "To view the results, use the cat command and type:"
echo "cat hello_mpi_gnu.log"

