#!/bin/bash
# This is the README file is an executable script.
# To run type: ./README
#
# EXAMPLE OBJECTIVE: to demonstrate omp_hello.c example 
# on Zythos with PGI compiler.
# omp_hello.c code is taken from
# https://computing.llnl.gov/tutorials/openMP/exercise.html
# This code is an OpenMP example that runs on 2 nodes with
# 6 cores and 6 OpenMP threads for each node.
# To run this code, we need to edit the partition,
# load the necessary modules
# and specify the total number of OpenMP threads.
# This information is located under hello_ompc_pgi.slurm
# You can edit the SLURM as: emacs hello_ompc_pgi.slurm


# SLURM directives
# 
# Here we specify to SLURM that we want 2 nodes (--ntasks=2)
# and 6 cores (--cpus-per-task=6)
# Then, we modify the partition to Zythos (--partition=zythos)
# We also replace the account name with 
# our own account name (--account=pawsey0001)
# If the account name is missing or not entered correctly,
# the SLURM does not run.
# To run this code correctly, we comment out: --export=NONE
# If this is not commented out, the code does not run.
# To compile the code with PGI, we need to unload 
# the gcc module and load the pgi module as shown below: 
# module unload gcc
# module load pgi
# We also need to load the necessary modules before module listing.
# module load mpt
# Then, we set the number of threads to 12 as shown below: 
# export OMP_NUM_THREADS=12
# Therefore, the srun looks like:
# omplace -nt $OMP_NUM_THREADS ./$EXECUTABLE >> ${OUTPUT}

# To compile the omp_hello.c code with PGI
pgcc -mp omp_hello.c -o hello_omp_pgi

# To submit the job to Zythos
sbatch hello_ompc_pgi.slurm

# To view when the job starts
squeue -u $USER

echo "Your jobID is returned with the sbatch command."
echo "Your job is deleted from the scratch."
echo "It is now moved to your group."
echo "Your results are now located in /${MYGROUP}/zythos_omp_pgi_results/"
echo "To change to your jobID directory, type:"
echo "cd /${MYGROUP}/zythos_omp_pgi_results/jobID/"
echo "To view the results, use the cat command and type:"
echo "cat hello_omp_pgi.log"
