# To run this make file
# make sure that the Intel compilers and MKl are loaded then type
#  make -f makefile.mkl 
# 

CFLAGS = -openmp -m64

# parallel mkl libs
LIBS = -lmkl_intel_lp64 -lmkl_core -lmkl_intel_thread -ldl -lpthread -lm

all: dgemm_ex.exe 

dgemm_ex.exe: dgemm_ex.c
	$(CC)  $(CFLAGS) $(CPPFLAGS) $(LFLAGS) -o dgemm_ex.exe dgemm_ex.c  $(LIBS)

clean:
	$(RM) *.exe

