#!/bin/bash
# This is the README file that is an executable script to demonstrate
# omp_hello.c example on Magnus.
# omp_hello.c is taken from https://computing.llnl.gov/tutorials/openMP/exercise.html
# To run this cod, specify the total number of processes per node
# and the number of processes per node.
# This information is located under hello_omp_c.slurm
# You can edit the SLURM as: emacs hello_omp_c.slurm

# SLURM directives
# 
# Here we specify to SLURM we want 2 nodes (--nodes=2)
# Replace the account name with your account name (--account=interns2016)
# To launch a job, we specify to aprun 48 MPI tasks (-n 48)
# with 24 tasks per node (-N 24)
# Therefore the aprun command: aprun -n 48 -N 24

# To compile the omp_hello.c code
ftn -O2 -h omp code_omp.f90

# To submit the job to Magnus
sbatch hello_omp_c.slurm

# To view when the job starts
squeue -u $USER

echo ¨Your jobID is returned with the sbatch command.¨
echo ¨Your job is deleted from the scratch.¨
echo ¨It is now moved to your group.¨
echo ¨Your results are now located in /${MYGROUP}/hello_omp_c_results/¨
echo ¨To change to your jobID directory, type:¨
echo ¨cd /${MYGROUP}/hello_omp_c_results/jobID/¨
echo ¨To view the results, use the cat command and type:¨
echo ¨cat hello_omp_c.log¨
