# To run this make file
# make sure that MKl is loaded then type
#  make -f makefile.mkl 
# 

CFLAGS = -O3 -qopenmp -m64

#parallel mkl libs
LIBS = -lmkl_intel_lp64 -lmkl_core -lmkl_gnu_thread -ldl -lpthread -lm


all: dgemm_ex.exe 

dgemm_ex.exe: dgemm_ex.c
	$(CC)  $(CFLAGS) $(CPPFLAGS) $(LFLAGS) -o dgemm_ex.exe dgemm_ex.c  $(LIBS)

clean:
	$(RM) *.exe

