#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate hello_mpi.f90 example
# on Magnus on the Intel environment with task placement.
# hello_mpi.f90 is an MPI code that runs with hyper-threading 
# which helps specifying how tasks bind to logical cores.
# hello_mpi.f90 code is taken from
# https://people.sc.fsu.edu/~jburkardt/f_src/hello_mpi/hello_mpi.f90
# cp the hello_mpi.f90 source code
cp $GE_DIR/hello_mpi.f90 .


# To run this code, we need to specify the total number of MPI tasks,
# the number of MPI tasks per node
# and the number of hyper threads per core.
# This information is located under task_placement_intel.slurm
# You can edit the SLURM as: emacs task_placement_intel.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1)
# To compile the code with Intel environment, we swap from
# Cray to Intel as shown below:
module swap PrgEnv-cray PrgEnv-intel
# To launch a job, we specify to aprun 48 MPI tasks (-n 48)
# with 48 tasks required on the node (-N 48)
# These tasks are accomodated using hyper-threading with
# two (hyper-) threads per core (-j 2).
# Therefore, the aprun command looks like: 
# aprun -n 48 -N 48 -j 2 ./$EXECUTABLE >> ${OUTPUT}

# To compile the hello_mpi.f90 code on Intel
ftn -O2 hello_mpi.f90 -o task_placement_intel

# To submit the job to Magnus
sbatch task_placement_intel.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_task_placement_intel/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/task_placement_intel_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/task_placement_intel_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat thread_placement_cray.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " "  
echo "more information about Magnus can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Magnus+User+Guide"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
