#!/bin/bash
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demostrate helloworld.c 
# with PGI compiler on Zeus. 
# To run this code, load the necessary modules.
# cp the helloworld.c source code
cp $GE_DIR/src/helloworld.c .


# This information is located under hello_pgi_c.slurm
# You can edit the SLURM as: emacs hello_pgi_c.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1)
# We the change the partition to --partition==workq
# To compile with PGI compiler, we need to unload
# the gcc module and load the PGI compiler as shown below:
module unload gcc
module load pgi
# To run the code, we simply type:
# ./$EXECUTABLE >> ${OUTPUT}

# To compile the helloworld.c code with PGI
pgcc -O2 helloworld.c -o helloworld_pgi

# To submit the job to Zeus
sbatch hello_pgi_c.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_helloC_pgi/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/helloC_pgi_results_zeus/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/helloC_pgi_results_zeus/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat helloC_pgi.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "
echo " "  
echo "more information about Zeus/Zython can be found at:"
echo " https://support.pawsey.org.au/documentation/pages/viewpage.action?pageId=2162999"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "

