#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBjECTIVE: to demostrate omp_hello.c example
# on Zeus with GNU compiler.
# omp_hello.c code is taken from
# https://computing.llnl.gov/tutorials/openMP/exercise.html
cp -r ../../src/megahit-example .

# This code is an OpenMP example that runs one 16-thread
# OpenMP instance with one node.

# To run this code load the necessary modules.
# and specify the total number of OpenMP threads.

# we need to load the gcc module as shown below: 

module load gcc/7.4.0 megahit/1.1.4

# Create a temp-storage directory and copy data and/or executables
# Note! copying executables is not needed if modules are used.

if [ ! -d $PG/data_exe ]; then
    mkdir $PG/data_exe
fi

# Then, we set the number of threads to 16 as shown below: 
# export OMP_NUM_THREADS=16


cp -r megahit-example $PG/data_exe/.
# sanity check that the executable is there
ls -al $PG/data_exe

# To submit the job to paragon
id=$(bsub < run_megahit.lsf)
jobid=`echo $id | awk '{print $2}' | sed 's/<//g' | sed 's/>//g'`

echo "The bsub command returns what the jobid is for this job."
echo "To check the status of your job, use the lsf command:"
echo "bjobs -u $USER"
echo " "
echo "Your job will be run in $PG/run_megahit/${jobid}."
echo " "
echo "Your results will be saved in ${HCCDS}/megahit_results_paragon/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYCDS}/megahit_results_paragon/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat megahit_ex.log"
echo " "

#  lets script run in background to until job finishes
while [[ ! -f $PG/cpt$jobid ]]; do
  sleep 2
done

#  Declare unique directory to store results
RESULTS=$HCCDS/megahit_results_paragon
###############################################
# Makes the unique directory in CDS directory for the results of this job
if [ ! -d $RESULTS ]; then 
    mkdir -p $RESULTS 
fi
echo the results directory is $RESULTS

# move results from scratch back to CDS
mv  ${PG}/run_megahit/$jobid  $RESULTS

###########################
# Clean up $SCRATCH 

rm -rf ${PG}/run_megahit/$jobid
rm ${PG}/cpt$jobid


