#!/bin/bash
# this is the README file the mom node example on magnus.
# It is to demonstrate the differences between the mom nodes
# and the compute nodes on magnus. WE usethe hostname command
# for this purpose

# To run this example just submit a job to magnus using
# the hostname.slurm script

sbatch hostname.slurm
echo "your jobid is returned with the sbatch command"
echo "the results from this job are moved to ${MYGROUP}/hostname_results/"

echo "To view the results change to the /${MYGROUP}/hostname_results"
echo "cd into the $JOBID directory" and use the cat command to inspect the
results"
echo "hostname.log file!"
