#!/bin/bash 
# this is the README file is an executable script to demonstrate 
# the mom node example on magnus.
# It is to show the differences between the mom nodes
# and the compute nodes on magnus.  We use the hostname command
# for this purpose.

# To run this example just submit a job to magnus using the 
# hostname.slurm script 

sbatch hostname.slurm
echo "your jobid is returned with the sbatch command"
echo "the results from this job are moved to /${MYGROUP}/hostname_results/"

echo "To view the results change to the /${MYGROUP}/hostname_results"
echo "cd into the $JOBID directory" and use cat command to inspect the 
echo "hostname.log file!"



