#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate swash openmp example 
# on kaya with the Intel compiler toolchain Environment.

# SWASH is a general-purpose numerical tool for simulating 
# unsteady, non-hydrostatic, free-surface, rotational flow 
# and transport phenomena in coastal waters as driven by waves, 
# tides, buoyancy and wind forces. It provides a general basis
# for describing wave transformations from deep water to a 
# beach, port or harbour, complex changes to rapidly varied 
# flows, and density driven flows in coastal seas, estuaries, 
# lakes and rivers.
 
# with 4 OpenMP threads on a node.
# To run this code, we need to specify the total 
# number of threads per node.
# This information is located under swan.slurm
# You can edit the SLURM as: nano swan.slurm 

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1 or -N 1)
# grasp is compiled with GNU, we change the compiler
# from GNU as shown below:
module load intel/2020.4 swash/9.01

# To launch a job, we specify the input file a13stw01.sws number of threads 20 (-n 20)

# Therefore, the run command looks like:
# swashrun -input a1101.sws -omp 20 >> ${OUTPUT}

# To submit the job to Kaya
jobid=$(sbatch --parsable swash.slm)

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_swash/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/swash_results_${case}/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/swash_results_${case}/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat a11stw01.prt"
echo " "
echo " kaya user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "
echo " "  
echo "more information about Kaya can be found at:"
echo " https://docs.hpc.uwa.edu.au/docs/"
echo " "
echo "more information about SLURM and srun can be found at:"
echo " https://docs.hpc.uwa.edu.au/docs/slurm/"
echo " "
echo " "
