#!/bin/bash
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBjECTIVE: to demostrate hybrid_hello.f90 example
# with thread placement on Magnus on the Cray environment. 
# cp the hybrid_hello.f90 source code
cp $GE_DIR/hybrid_hello.f90 .


# This is a hybrid MPI/OpenMP job where we run 24 MPI tasks
# with 2 OpenMP threads per MPI task.
# To run this code, we need to specify the number of MPI tasks,
# the number of MPI tasks per node,
# the number of threads per each task which are also 
# the hyper-threads per core.
# This information is located under thread_placement_cray.slurm
# You can edit the SLURM as: emacs thread_placement_cray.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--node=1)
# Then, we set the total number of threads to 2
# export OMP_NUM_THREADS=2
# To launch a job, we specify to aprun 24 MPI tasks (-n 24)
# with 24 MPI tasks on each node (-N 24).
# with 2 threads for each task (-d 2)
# and these are hyper-threads per core (-j 2).
# Therefore, the aprun command looks like:
# aprun -n 24 -N 24 -d 2 -j 2 ./$EXECUTABLE  >> ${OUTPUT}

# To compile the hybrid_hello.f90 code on Cray
ftn -O2 -h omp hybrid_hello.f90 -o thread_placement_cray

# To submit the job to Magnus
sbatch thread_placement_cray.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_thread_placement_cray/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/thread_placement_cray_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/thread_placement_cray_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat thread_placement_cray.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " "  
echo "more information about Magnus can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Magnus+User+Guide"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
