#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
# 
# Example OBJECTIVE: to demonstrate hello_world.f90 example 
# with PGI compiler on Zeus.
# hello_world.f90 is a simple FORTRAN code prints "Hello World!" 
# and runs on a single node.
# To run this code, we need to specify the number of nodes used
# and change from GNU compiler to PGI.
# This information is located under hello_fortran_pgi.slurm
# You can edit the SLURM as: emacs hello_fortran_pgi.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1)
# We then change the partition to --partition=workq
# To run this code correctl, we need to remove --export=NONE
# If this is included in the SLURM, the code does not run properly.
# To compile this code with PGI, we swap
# from GNU to PGI as shown below:
# module unload gcc
# module load pgi
# To run the code, we simply type:
# ./$EXECUTABLE >> ${OUTPUT}

# To compile the hello_world.f90 code with PGI
pgf90 -O2 hello_world.f90 -o hello_fortran_pgi

# To submit the job to Zeus
sbatch hello_fortran_pgi.slurm

echo "The sbatch command returns what jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo "Your job is deleted from the scratch."
echo "It is now moved to your group."
echo "Your results are now located in ${MYGROUP}/hellofortran_pgi_results_zeus/"
echo "To change to your jobID directory, type:"
echo "cd ${MYGROUP}/hellofortran_pgi_results_zeus/jobID/"
echo "To view the results, use the cat command and type:"
echo "cat hello_fortran_pgi.log"
