#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate hello_world.f90 example 
# in Cray environment on Magnus.
# hello_world.f90 is a serial FORTRAN code and 
# It prints "Hello World!" and runs on a single node.
# cp the hello_world.f90 source code
cp $GE_DIR/hello_world.f90 .


# To run this code, we need to specify the number of nodes used.
# This information is located under hello_fortran_cray.slurm
# You can edit the SLURM as: emacs hello_fortran_cray.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1)
# To run the code, we simply type:
# aprun -n 1 ./$EXECUTABLE >> ${OUTPUT}

# To compile the hello_world.f90 code
ftn -O2 hello_world.f90 -o hello_fortran_cray

# To submit the job to Magnus
sbatch hello_fortran_cray.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_fortran_helloworld_cray/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/fortran_helloworld_cray_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/fortran_helloworld_cray_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat fortran_helloworld_cray.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "

echo " "  
echo "more information about Magnus can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Magnus+User+Guide"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
