#!/bin/bash
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate helloworld.c example
# on Zythos with GNU compiler.
# helloworld.c is a simple c code that prints out "Hello World!"
# and runs on a single node.
# cp the helloworld.c source code
cp $GE_DIR/src/helloworld.c .


# To run this code, we need to specify the number of nodes used
# and edit the partition and load the necessary modules.
# This information is located under helloworld_gnuc.slurm
# You can edit the SLURM as: emacs helloworld_gnuc.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--ntasks=1)
# We then change the partition to Zythos (--partition==zythos)
# We also edit the account name (--account=pawsey0001)
# If the account name is missing or not entered correctly,
# the SLURM does not run.
# To run this code correctly on Zythos, we need to remove --export=NONE
# If it is still included in the SLURM, the code does not compile
# To compile this code with GNU compiler, we load the gcc
# module as shown below:
module load gcc
# To run the code, we simply type:
# ./$EXECUTABLE >> {$OUTPUT}

# To compile the helloworld.c with GNU
gcc -O2 helloworld.c -o helloworld_gnu

# To submit the job to Zythos
sbatch helloworld_gnuc.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_HelloC_gnu_zythos/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/HelloC_gnu_zythos_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/HelloC_gnu_zythos_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat HelloC_gnu_zythos.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "
echo " "  
echo "more information about Zythos can be found at:"
echo " https://support.pawsey.org.au/documentation/pages/viewpage.action?pageId=2162999"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
