#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate helloworld.c example 
# in Intel environment on Magnus.
# helloworld.c is a simple c code that prints "Hello World!" 
# and runs on a single node.
# cp the helloworld.c source code
cp $GE_DIR/src/helloworld.c .


# To run this code, we need to specify the number of nodes used.
# This information is located under helloworld_intel.slurm
# You can edit the SLURM as: emacs helloworld_intel.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1)
# To compile the code with the Intel environment, we change
# the environment from Cray to Intel as shown below:
module swap PrgEnv-cray PrgEnv-intel
# To run the code, we simply type:
# aprun -n 1 ./$EXECUTABLE >> ${OUTPUT}

# To compile the helloworld.c code on Intel
cc -O2 helloworld.c -o helloworld_intel

# To submit the job to Magnus
sbatch helloworld_intel.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_helloC_intel/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/helloC_intel_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/helloC_intel_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat helloC_intel.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "

echo " "  
echo "more information about Magnus can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Magnus+User+Guide"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
