#!/bin/bash
# This is the README file is an executable script.
# It prints out the simple codes of helloworld.c
# To run type: ./README_gnu
#
# Example OBjECTIVE: to demostrate helloworld.c example
# on Zeus. 
# To run this code, edit the partition and 
# load the necessary modules.
# This information is located under helloworld_gnu_c.slurm
# You can edit the SLURM as: emacs helloworld_gnu_c.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 1 node (--nodes=1)
# Change the partition to the GPU partition (--partition==workq)
# Add #SBATCH --gres=gpu:1
# Load the necessary modules before module listing.
# module load gcc

# To compile the gnu code

gcc -O2 helloworld.gnu.c -o helloworld_gnu

# To submit the job to Magnus

sbatch helloworld_gnu.slurm

echo "The sbatch command returns what jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo "Your job is deleted from the scratch."
echo "It is now moved to your group."
echo "Your results are now located in ${MYGROUP}/hello_gnu_results/"
echo "To change to your jobID directory, type:"
echo "cd ${MYGROUP}/helloworld_gnu_results/jobID/"
echo "To view the results, use the cat command and type:"
echo "cat helloworld.gnu.log"
