#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate hello_mpi.c example on Magnus
# with Cray Environment.
# hello_mpi.c code is taken from
# https://www.dartmouth.edu/~rc/classes/intro_mpi/hello_world_ex.html
# cp the hello_mpi.c source code
cp $GE_DIR/hello_mpi.c .


# hello_mpi.c is an MPI code that runs on 2 nodes 
# with 24 MPI tasks on each node.
# To run this code, we need to specify the total number of MPI tasks
# and the number of MPI tasks per node.
# This information is located under hello_mpi_cray.slurm
# You can edit the SLURM as: emacs hello_mpi_cray.slurm &

# SLURM directives
# 
# Here we specify to SLURM we want 2 nodes (--nodes=2)
# To launch a job, we specify to aprun 48 MPI tasks (-n 48)
# with 24 tasks per node (-N 24)
# Therefore, the aprun command looks like:
# aprun -n 48 -N 24 ./$EXECUTABLE >> ${OUTPUT}

# To compile the hello_mpi.c code on Cray
cc -O2 hello_mpi.c -o hello_mpi_cray

# To submit the job to Magnus
sbatch hello_mpi_cray.slurm
jobid=`squeue -u $USER | grep $USER | awk '{print $1}'`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_hello_mpi_c_cray/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/hello_mpi_c_cray_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/hello_mpi_c_cray_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat thread_placement_cray.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " "  
echo "more information about Magnus can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Magnus+User+Guide"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
