#!/bin/bash --login
# This is the README file is an executable script.
# To run type: ./README
#
# Example OBJECTIVE: to demonstrate hello_mpi.c example on kaya 
# with Intel Environment.
# hello_mpi.c code is taken from
# https://www.dartmouth.edu/~rc/classes/intro_mpi/hello_world_ex.html
# cp the hello_mpi.c source code
cp $GE_DIR/src/hello_mpi.c .


# hello_mpi.c is an MPI code that runs on 2 nodes 
# with 36 MPI tasks on each node.
# To run this code, we need to specify the total number of MPI tasks
# and the number of MPI tasks per node.
# We also need to change the compiler from Cray to Intel
# to be able to run this code with Intel Environment.

# SLURM directives
# 
# Here we specify to SLURM we want 2 nodes (--nodes=2)
# To compile hello_mpi.c with Intel, we load the intel compiler :
module intel/2020.4
# To launch a job, we specify to srun 36 MPI tasks (-n 36)
# with 36 tasks per node (--ntasks=36)
# Therefore, the aprun command looks like:
# srun -n 36 -N 1 ./$EXECUTABLE >> ${OUTPUT}

# To compile the hello_mpi.c code with Intel
cc -O2 hello_mpi.c -o hello_mpi_intel

# To submit the job to Magnus
sbatch hello_mpi_intel.slurm
jobid=`sbatch --parsable hello_mpi_intel.slurm`

echo "The sbatch command returns what the jobid is for this job."
echo "To check the status of your job, use the slurm command:"
echo "squeue -u $USER"
echo " "
echo "Your job will be run in $MYSCRATCH/run_hello_mpi_c_intel/${jobid}."
echo " "
echo "Your results will be saved in ${MYGROUP}/hello_mpi_c_intel_results/${jobid}"
echo "and the scratch directory will then be deleted."
echo " "
echo "To check the results change to your jobid directory, type:"
echo "cd ${MYGROUP}/hello_mpi_c_intel_results/${jobid}"
echo " " 
echo "To view the results, use the cat command and type:"
echo "cat hello_mpi_c_intel.log"
echo " "
echo " PAWSEY user shortcuts! " 
echo  '$MYSCRATCH' "is an environment variable it is set to $MYSCRATCH"
echo  '$MYGROUP' "is an environment variable it is set to $MYGROUP"
echo " example:  cd \$MYGROUP "

echo " "  
echo "more information about Magnus can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Magnus+User+Guide"
echo " "
echo "more information about SLURM and aprun can be found at:"
echo " https://support.pawsey.org.au/documentation/display/US/Scheduling+and+Running+Jobs"
echo " "
echo " "
